Add page for game servers under 'Other Services'.
SRCF/docs pull request #34
Opened 2021-04-05 14:24 UTC by AndyJenks

Hopefully I have inferred correctly the proper way to do things. Certainly it seemed to work for me locally.

2021-04-05 16:35 UTC, CHTJonas requested changes
Looks good! :tada:

One small thing: as per #35 I think it's been decided to retire the `userservers.srcf.net` hostname because it's a CNAME for `cavein`, which has now been decommissioned; switching it over to point at `doom` would cause SSH host key mismatch warnings so best to have people SSH to `doom` directly.

2021-04-05 16:35 UTC, CHTJonas commented on source/services/gameserver.rst
> +long-running application) you should use ``userservers.srcf.net``, as
```suggestion
long-running application) you should use ``doom.srcf.net``, as 
```

2021-04-06 21:51 UTC, doismellburning approved these changes

2021-04-06 23:33 UTC, CHTJonas approved these changes
The sysadmins may wish to comment on the "1GB of RAM" part specifically but LGTM! 🚀

2021-04-09 21:33 UTC, rsa33 approved these changes
There's apparently also a `nogui` option (or `--nogui`?), but in the interests of keeping the example broader (and because hopefully MC knows not to try and launch a GUI for users without a graphical session), let's keep it as-is.

2021-04-09 21:35 UTC, merged