Tidy up code snippets
SRCF/docs pull request #48
Opened 2022-02-28 23:30 UTC by rsa33

There's a handful of changes here related to fenced code blocks across the docs:

* 4-space indents have been removed (they appear verbatim in the rendered code)
* code block types have been set to `text` when missing (to avoid inconsistent non-highlight rendering)
* certain invalid keywords like `irc` have been substituted
* shell command blocks now use a CSS-positioned `$` so it doesn't get copied when selecting the block
  * shell session examples now use the `text` type (note that `bash-session` isn't available in our version of Hugo)
  * bash scripts use the `sh` type

This PR should cover my list of considerations in https://github.com/SRCF/docs/pull/47#issuecomment-1050833907.

2022-02-28 23:50 UTC, edwinbalani requested changes
Thanks, looks very nice per the preview link you sent me!

There were a handful of inaccuracies/inconsistencies in the content, but I haven't flagged any of the ones you didn't touch with your changes -- so there's only one place to look at again.

If I understand properly, we're using the 'bash' highlighting language for a shell session and 'sh' for shell script snippets.

Also, what are the 'Go' and 'Markdown' types in the metadocs?  Do the capital letters mean anything special?

2022-02-28 23:50 UTC, edwinbalani commented on content/reference/shell-and-files/scheduled-tasks.md
> +    sudo -Hu soc XDG_RUNTIME_DIR=/run/user/$(id -u $soc) '$@'
`sudo -Hu $soc`

2022-02-28 23:50 UTC, edwinbalani commented on content/reference/shell-and-files/scheduled-tasks.md
> +    sudo -Hu soc XDG_RUNTIME_DIR=/run/user/$(id -u $soc) '$@'
Probably want `"$@"`?

2022-02-28 23:57 UTC, edwinbalani approved these changes

2022-02-28 23:58 UTC, rsa33 commented
> If I understand properly, we're using the 'bash' highlighting language for a shell session and 'sh' for shell script snippets.

That is correct.

> Also, what are the 'Go' and 'Markdown' types in the metadocs?

I'm not sure why they're using Go currently (because Hugo is Go?) -- they're examples of snippets to be included in content files themselves, so Markdown seems the most appropriate choice, though it's bespoke syntax and doesn't really highlight usefully in any of them.

> Do the capital letters mean anything special?

It's case-insensitive as far as I can tell, so I've left the existing ones as-is to reduce the noise a bit.

2022-02-28 23:58 UTC, CMTC commented
Perhaps it's a problem that is fine to ignore, but the css-trickery obviously only works in sufficiently clever browsers. Netsurf and the text-only browsers I've tried are not sufficiently clever.

2022-03-01 00:01 UTC, edwinbalani commented
> Perhaps it's a problem that is fine to ignore, but the css-trickery obviously only works in sufficiently clever browsers.

So long as the behaviour in those browsers is for the prefix to just not appear, should we be OK?  Call it "progressive CSS" I suppose.

2022-03-01 00:02 UTC, edwinbalani commented
> I'm not sure why they're using Go currently (because Hugo is Go?)

I think Hugo's templating language is really just Go templates.

2022-03-01 00:03 UTC, CMTC commented
> So long as the behaviour in those browsers is for the prefix to just not appear, should we be OK? Call it "progressive CSS" I suppose.

That indeed seems to be the case. Surely since the symbol was previously shown, but is now not, we should regard it as regressive CSS...

2022-03-01 10:39 UTC, rsa33 commented
> I think Hugo's templating language is really just Go templates.

Upon closer inspection of the highlighters list, I think what we actually want here is `go-text-template` (which is supported in our version of Hugo).

2022-03-25 07:56 UTC, rsa33 commented
It has been noted that the CSS-applied `$` doesn't appear for each line of a multi-line command block, but that's an acceptable compromise for now.

2022-03-25 07:57 UTC, merged